# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: cd StoreApplication && dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SonarCloudAnalyze@1
  displayName: Run SonarCloud Analysis

- task: SonarCloudPrepare@1
  displayName: Prepare SonarCloud Analysis
  inputs:
    SonarCloud: 'sonarcloud-ansimi'
    organization: 'ansimi'
    scannerMode: 'MSBuild'
    projectKey: 'gamestore'
    projectName: 'The Video Game Store'
    
- task: SonarCloudPublish@1
  displayName: Publish SonarCloud Analysis
  inputs:
    pollingTimeoutSec: '300'